version: '3.8'

volumes:
  mongo: null

services:

  mongo:
    image: mongo:5.0.5
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: app
      MONGO_INITDB_ROOT_PASSWORD: app
    volumes:
      - mongo:/data/db

  mongo-express:
    image: mongo-express:0.54
    depends_on:
      - mongo
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: app
      ME_CONFIG_MONGODB_ADMINPASSWORD: app
      ME_CONFIG_MONGODB_URL: mongodb://app:app@mongo:27017/
      ME_CONFIG_SITE_BASEURL: "/mongo-express/"

  server:
    build: ./server
    depends_on:
      - mongo
      - mongo-express
    restart: always
    volumes:
      - ./server/src:/opt/server/src

  nginx:
    build:
      dockerfile: ../nginx/Dockerfile
      context: ./build
    restart: always
    ports:
      - 8000:8000
    env_file:
      - ./build/nginx.env
