services:

  code-server:
    restart: "no"
    build:
      context: ../docker-contexts/code-server
    volumes:
      - ..:/opt/app
      - ../build.config.json:/opt/config.json
      - node_modules:/opt/app/node_modules
      - scratch_volume:/opt/app/scratch_volume
