services:

  express:
    build:
      context: ../docker-contexts/node
    restart: always
    volumes:
      - ../build/config.json:/opt/config.json
      - ../src:/opt/app/src
      - ../misc:/opt/app/misc
      - node_modules:/opt/app/src/node_modules
    command: bash -c 'misc/setup_node_container && echo "running express" && cd src/express && npx nodemon --watch .. ./server.js'

  # nginx:
  #   depends_on:
  #     - express
  # this dependency is not used, since the nginx container will repeatedly restart until the `express` hostname resolves
