services:

  express:
    build:
      dockerfile: ./src/Dockerfile
      context: ..
    restart: always
    volumes:
      - ../src:/opt/app/src
      - ../package.json:/opt/app/package.json
      - ../package-lock.json:/opt/app/package-lock.json
      - node_modules:/opt/app/node_modules
    command: bash -c 'src/scripts/setup_node_container && echo "running express" && cd src/express && npx nodemon ./server.js'

  # nginx:
  #   depends_on:
  #     - express
  # this dependency is not used, since the nginx container will repeatedly restart until the `express` hostname resolves
