services:

  jupyter:
    restart: "no"
    build:
      context: ../docker-contexts/jupyter
    volumes:
      - ..:/opt/app
      - node_modules:/opt/app/node_modules
      - scratch_volume:/opt/app/scratch_volume

    # NOTE 8/6/22: node packages are now installed via `npm-install-if-needed` script called from run script
    # command: bash -c "misc/setup_node_container && npx tslab install && ln -s /opt/app/node_modules/.bin/tslab /usr/local/bin/ && echo 'running jupyter' && jupyter lab --notebook_dir=/opt/app --ip='*' --port=8003 --no-browser --allow-root --NotebookApp.allow_origin='*' --NotebookApp.base_url='/jupyter' --NotebookApp.password='' --NotebookApp.token=''" --NotebookApp.use_redirect_file=false
    command: bash -c "echo 'WHOAMI:' && whoami && mkdir /root/.local && chmod 777 /root && chmod 777 /root/.local && npx tslab install && ln -s /opt/app/node_modules/.bin/tslab /usr/local/bin/ && echo 'running jupyter' && jupyter lab --notebook_dir=/opt/app --ip='*' --port=8003 --no-browser --allow-root --NotebookApp.allow_origin='*' --NotebookApp.base_url='/jupyter' --NotebookApp.password='' --NotebookApp.token=''" --NotebookApp.use_redirect_file=false
