version: '3.8'

volumes:

  nginx_etc_letsencrypt: null

services:

  next:
    build: ../next
    restart: always
    volumes:
      - ../next/src:/opt/next/src
    command: bash -c 'echo "running next in prod mode" && npx next build && npx next start -p 8001'

  nginx:
    build:
      dockerfile: ../nginx/Dockerfile
      context: ../build
    depends_on:
      - next
    restart: always
    volumes:
      - ../nginx/run:/opt/run
      - nginx_etc_letsencrypt:/etc/letsencrypt
    env_file:
      - ../build/nginx.env
