version: '3.8'

services:

  next:
    build: ../next
    restart: always
    volumes:
      - ../next/src:/opt/next/src

  nginx:
    build:
      dockerfile: ../nginx/Dockerfile
      context: ../build
    depends_on:
      - next
    restart: always
    ports:
      - 8000:8000
