services:

  node:
    restart: "no"
    build:
      context: ../docker-contexts/node
    volumes:
      - ..:/opt/app
      - ${runtime_filename}:/opt/runtime-config.json
      - ${deployment_state_filename}:/opt/deployment.json
      - node_modules:/opt/app/node_modules
