version: '3.8'

volumes:

  test_node_modules: null

services:

  test:
    build:
      context: ../docker-contexts/test
    restart: "no"
    network_mode: "host"
    volumes:
      - test_node_modules:/opt/test/node_modules
      - ../test/specs:/opt/test/specs
      - ../test/package.json:/opt/test/package.json
      - ../test/package-lock.json:/opt/test/package-lock.json
    command: bash -c 'echo "127.0.0.1 localhost" > /etc/hosts && flock node_modules/flock-for-multi-container-installs npm install && cd /opt/test && (Xvfb :99 -screen 0 1024x768x16 -ac -nolisten tcp -nolisten unix & echo starting test & CHROMIUM_INSIDE_DOCKER=1 DISPLAY=:99 npm test)'
